[package]
name = "skyes-silly-rt"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
image = { version = "0.25.8", features = ["png", "rayon"], default-features = false }
indicatif = { version = "0.18.0", features = ["rayon"] }
knus = "3.3.1"
rand = "0.9.2"
rand_xoshiro = "0.7.0"
rayon = "1.11.0"
stl_io = "0.8.5"
